name: CD Workflow

on:
    workflow_run:
        workflows: ["Github-Actions"]
        types:
            - completed

jobs:
    deploy:
        if: ${{github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run a one-line script
              run: echo Building the docker image
            - name: Building docker image
              run: docker build -t my-node-app .
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Tagging docker image
              run: docker tag my-node-app ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest
            - name: Pushing docker image
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest