name: Github-Actions

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run a one-line script
              run: echo Hello, world
            - name: install dependencies
              run : npm install
            - name: run tests
              run : npm test