name: My Workflow

env:
    MY_VARIABLE: This is a variable

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run a one-line script
              run: echo Hello, world
            - name : show the variable
              run: echo ${{ env.MY_VARIABLE }}
            - name : print the secret
              run: echo ${{ secrets.MY_SECRET }}
            - name : Create a file 
              run: echo "Hello, world" > hello.txt
            - name : read the hello file
              run: cat hello.txt